# Generated by Django 4.2.3 on 2023-10-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
    ]
